POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpc2lpcmkiLCJpZCI6IjVlMzJkNzA5ODA0NGJlNGVmMmM0OTFiMiIsImlhdCI6MTU4MDQ2NjI3M30.ONosW6sd8SmBxZQ8Gxlyfv20REjDV8JYa5G745pAUsA
 
{
    "title": "Joo",
    "content": [
        {
            "title": "Hieno a)",
            "content": "upeeta"
        },
        {
            "title": "hieno b)",
            "content": "loistavaa"
        }
    ]
}

###
POST  http://localhost:3001/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpc2lpcmkiLCJpZCI6IjVlMzJkNzA5ODA0NGJlNGVmMmM0OTFiMiIsImlhdCI6MTU4MDQ2NjI3M30.ONosW6sd8SmBxZQ8Gxlyfv20REjDV8JYa5G745pAUsA
 
{
    "title": "Homework one",
    "content": [
        {
            "title": "d) Mitä lisenssiä kukin näistä ohjelmista käyttää? Selitä lyhyesti, mitä oikeuksia ja velvolisuuksia tuosta lisenssistä seuraa.",
            "content": "Git ja htop ovat julkaistu lisenssillä GNU2(General Public Licenseversion 2.0), joka on yksi avoimista lisensseistä.Jos ohjelma käyttää GNU2 lisenssiä sitä saa käyttää, jakaa, kopioida,muokata ja käyttää opiskeluun vapaasti. Jos kuitenkin tekee muutoksiatällaiseen ohjelmaan, lisenssiä ei saa vaihtaa. Muutoksia tehdessä onmyös tehtävä selväksi, että tuotetta on muokattu. Visual studiocode on taas julkaistu MIT lisenssillä, joka on myös avoimien lisessienjoukossa. MIT lisenssillä julkaistuja ohjelmia saa kuitenkin myydäeteenpäin toisella lisenssillä. Se on siis vielä vapaampi kuin GNU2lisenssi."
        },
        {
            "title": "c) Asenna kolme itsellesi uutta ohjelmaa. Kokeile kutakin ohjelmaa senpääasiallisessa käyttötarkoituksessa.",
            "content": "Aluksi avasin terminaalin painamalla ctrl+alt+t. Terminaalissa ajoin'sudo apt-get update && sudo apt-get upgrade'. Tämän jälkeen asensinhtop ohjelman ajamalla komennon sudo apt-get install -y htop. Seuraavanaoli gitin vuoro ajamalla komento 'sudo apt-get install -y git'.Viimeisenä latasin visual studio coden käymällä sivustolla'https://code.visualstudio.com/Download' ja lataamalla 64 bit versionubuntu/debian käyttöjärjestelmille. Terminaalissa menin kohtaanDownloads ajamalla komennon 'cd Downloads'. Viimeisenä ajoin komennon'sudo dpkg -i code_1.26.0-1534177765_amd64.deb', jonka jälkeen minullaoli visual studio code koneellani. Ajoin komennon htop, josta näintietokoneeni suoritustietoja ja muistin tilanteen käyttöjärjestelmässä.Visual studiota ja gittiä kokeilin avaamalla vs coden ja luomalla uudenprojektin. Alustin uuden react projektin (tämä kyseinen verkkosivusto)ja puskin sen github repositoryyn käyttämällä git cli:tä."
        }
    ]
}
