
POST http://localhost:3001/api/blogs
Content-Type: application/json,
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpc2lpcmkiLCJpZCI6IjVlMzJkNzA5ODA0NGJlNGVmMmM0OTFiMiIsImlhdCI6MTU4MDQ2NTI1M30.tGQ2WsjgZA70JR74XuFjFHFQCnuiiW2hDJFpuwYxgMI

{
    "title": "Homework one",
    "content": "Yahoo"
}
###

POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "visiiri",
    "password": "tomsu<3"
}